#!/usr/bin/env bash
# Runs inside the temp postgres server started by the Docker entrypoint.
# Applies postgresql.conf settings that require a server reload/restart,
# then restarts the temp server so subsequent .sql init scripts see them.
set -euo pipefail

PGDATA="${PGDATA:-/var/lib/postgresql/data}"
CONF="${PGDATA}/postgresql.conf"

cat >> "$CONF" <<'EOF'

# ── pg-vector-age defaults ──────────────────────────────────────────────────
shared_preload_libraries = 'citus,age'

# Auth
password_encryption = 'scram-sha-256'

# TLS (certs generated by entrypoint.sh on first start)
ssl = on
ssl_cert_file = '/var/lib/postgresql/tls/server.crt'
ssl_key_file  = '/var/lib/postgresql/tls/server.key'

# Audit logging — connections, disconnections, DDL
log_connections    = on
log_disconnections = on
log_statement      = 'ddl'
log_line_prefix    = '%t [%p]: user=%u,db=%d,app=%a,client=%h '
EOF

echo "pg-vector-age: applied postgresql.conf — restarting temp server"
pg_ctl restart -D "$PGDATA" -o "-c listen_addresses=''" -w
echo "pg-vector-age: temp server restarted — extensions will load"
